import { Goal } from "../hooks/useQueries";

export interface LocalExercise {
  id: number;
  name: string;
  primaryMuscles: string[];
  category: string;
  goal: Goal;
  equipment?: string;
}

export const ALL_EXERCISES: LocalExercise[] = [
  // ── CHEST ──
  {
    id: 1001,
    name: "Barbell Bench Press",
    primaryMuscles: ["Chest", "Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 1002,
    name: "Incline Barbell Bench Press",
    primaryMuscles: ["Upper Chest", "Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 1003,
    name: "Decline Barbell Bench Press",
    primaryMuscles: ["Lower Chest", "Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 1004,
    name: "Dumbbell Bench Press",
    primaryMuscles: ["Chest", "Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 1005,
    name: "Incline Dumbbell Press",
    primaryMuscles: ["Upper Chest"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 1006,
    name: "Decline Dumbbell Press",
    primaryMuscles: ["Lower Chest"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 1007,
    name: "Push-Up",
    primaryMuscles: ["Chest", "Triceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 1008,
    name: "Wide-Grip Push-Up",
    primaryMuscles: ["Chest"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 1009,
    name: "Diamond Push-Up",
    primaryMuscles: ["Triceps", "Chest"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 1010,
    name: "Decline Push-Up",
    primaryMuscles: ["Upper Chest"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 1011,
    name: "Incline Push-Up",
    primaryMuscles: ["Lower Chest"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 1012,
    name: "Cable Chest Fly",
    primaryMuscles: ["Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 1013,
    name: "Dumbbell Chest Fly",
    primaryMuscles: ["Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 1014,
    name: "Incline Dumbbell Fly",
    primaryMuscles: ["Upper Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 1015,
    name: "Pec Deck Machine",
    primaryMuscles: ["Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 1016,
    name: "Chest Dip",
    primaryMuscles: ["Chest", "Triceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 1017,
    name: "Cable Crossover",
    primaryMuscles: ["Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 1018,
    name: "Low Cable Crossover",
    primaryMuscles: ["Upper Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 1019,
    name: "Smith Machine Bench Press",
    primaryMuscles: ["Chest", "Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 1020,
    name: "Chest Press Machine",
    primaryMuscles: ["Chest"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 1021,
    name: "Landmine Press",
    primaryMuscles: ["Upper Chest", "Shoulders"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 1022,
    name: "Svend Press",
    primaryMuscles: ["Chest"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Plate",
  },

  // ── BACK ──
  {
    id: 2001,
    name: "Deadlift",
    primaryMuscles: ["Back", "Glutes", "Hamstrings"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 2002,
    name: "Sumo Deadlift",
    primaryMuscles: ["Glutes", "Hamstrings", "Back"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 2003,
    name: "Romanian Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes", "Lower Back"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 2004,
    name: "Barbell Row",
    primaryMuscles: ["Back", "Biceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 2005,
    name: "Pendlay Row",
    primaryMuscles: ["Upper Back", "Lats"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 2006,
    name: "Dumbbell Row",
    primaryMuscles: ["Lats", "Rhomboids"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 2007,
    name: "T-Bar Row",
    primaryMuscles: ["Middle Back", "Lats"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 2008,
    name: "Pull-Up",
    primaryMuscles: ["Lats", "Biceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 2009,
    name: "Chin-Up",
    primaryMuscles: ["Lats", "Biceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 2010,
    name: "Wide-Grip Pull-Up",
    primaryMuscles: ["Lats"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 2011,
    name: "Neutral-Grip Pull-Up",
    primaryMuscles: ["Lats", "Biceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 2012,
    name: "Lat Pulldown",
    primaryMuscles: ["Lats"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 2013,
    name: "Wide-Grip Lat Pulldown",
    primaryMuscles: ["Lats"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 2014,
    name: "Close-Grip Lat Pulldown",
    primaryMuscles: ["Lats", "Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 2015,
    name: "Seated Cable Row",
    primaryMuscles: ["Middle Back", "Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 2016,
    name: "Face Pull",
    primaryMuscles: ["Rear Deltoids", "Rhomboids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 2017,
    name: "Hyperextension",
    primaryMuscles: ["Lower Back", "Glutes"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 2018,
    name: "Good Morning",
    primaryMuscles: ["Lower Back", "Hamstrings"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 2019,
    name: "Rack Pull",
    primaryMuscles: ["Upper Back", "Traps"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 2020,
    name: "Inverted Row",
    primaryMuscles: ["Back", "Biceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 2021,
    name: "Machine Row",
    primaryMuscles: ["Back"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 2022,
    name: "Meadows Row",
    primaryMuscles: ["Lats", "Teres Major"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 2023,
    name: "Cable Straight-Arm Pulldown",
    primaryMuscles: ["Lats"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 2024,
    name: "Shrugs",
    primaryMuscles: ["Traps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 2025,
    name: "Dumbbell Shrugs",
    primaryMuscles: ["Traps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 2026,
    name: "Trap Bar Deadlift",
    primaryMuscles: ["Quads", "Back", "Glutes"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Trap Bar",
  },
  {
    id: 2027,
    name: "Deficit Deadlift",
    primaryMuscles: ["Back", "Hamstrings"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },

  // ── SHOULDERS ──
  {
    id: 3001,
    name: "Barbell Overhead Press",
    primaryMuscles: ["Shoulders", "Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 3002,
    name: "Seated Dumbbell Shoulder Press",
    primaryMuscles: ["Shoulders"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 3003,
    name: "Standing Dumbbell Shoulder Press",
    primaryMuscles: ["Shoulders", "Core"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 3004,
    name: "Arnold Press",
    primaryMuscles: ["Shoulders"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 3005,
    name: "Lateral Raise",
    primaryMuscles: ["Side Deltoids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 3006,
    name: "Cable Lateral Raise",
    primaryMuscles: ["Side Deltoids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 3007,
    name: "Front Raise",
    primaryMuscles: ["Front Deltoids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 3008,
    name: "Cable Front Raise",
    primaryMuscles: ["Front Deltoids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 3009,
    name: "Reverse Fly",
    primaryMuscles: ["Rear Deltoids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 3010,
    name: "Cable Reverse Fly",
    primaryMuscles: ["Rear Deltoids"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 3011,
    name: "Upright Row",
    primaryMuscles: ["Shoulders", "Traps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 3012,
    name: "Machine Shoulder Press",
    primaryMuscles: ["Shoulders"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 3013,
    name: "Behind-the-Neck Press",
    primaryMuscles: ["Shoulders"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 3014,
    name: "Push Press",
    primaryMuscles: ["Shoulders", "Triceps", "Legs"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 3015,
    name: "Handstand Push-Up",
    primaryMuscles: ["Shoulders", "Triceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 3016,
    name: "Bradford Press",
    primaryMuscles: ["Shoulders"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },

  // ── BICEPS ──
  {
    id: 4001,
    name: "Barbell Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 4002,
    name: "EZ-Bar Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "EZ-Bar",
  },
  {
    id: 4003,
    name: "Dumbbell Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 4004,
    name: "Hammer Curl",
    primaryMuscles: ["Brachialis", "Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 4005,
    name: "Incline Dumbbell Curl",
    primaryMuscles: ["Biceps Long Head"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 4006,
    name: "Concentration Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 4007,
    name: "Preacher Curl",
    primaryMuscles: ["Biceps Short Head"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 4008,
    name: "Cable Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 4009,
    name: "Cable Hammer Curl",
    primaryMuscles: ["Brachialis"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 4010,
    name: "Reverse Curl",
    primaryMuscles: ["Brachioradialis", "Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 4011,
    name: "Zottman Curl",
    primaryMuscles: ["Biceps", "Brachioradialis"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 4012,
    name: "21s Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 4013,
    name: "Spider Curl",
    primaryMuscles: ["Biceps Short Head"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 4014,
    name: "Machine Curl",
    primaryMuscles: ["Biceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },

  // ── TRICEPS ──
  {
    id: 5001,
    name: "Tricep Dip",
    primaryMuscles: ["Triceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 5002,
    name: "Close-Grip Bench Press",
    primaryMuscles: ["Triceps", "Chest"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 5003,
    name: "Skull Crusher",
    primaryMuscles: ["Triceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 5004,
    name: "EZ-Bar Skull Crusher",
    primaryMuscles: ["Triceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "EZ-Bar",
  },
  {
    id: 5005,
    name: "Cable Tricep Pushdown",
    primaryMuscles: ["Triceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 5006,
    name: "Rope Tricep Pushdown",
    primaryMuscles: ["Triceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 5007,
    name: "Overhead Tricep Extension",
    primaryMuscles: ["Triceps Long Head"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 5008,
    name: "Cable Overhead Tricep Extension",
    primaryMuscles: ["Triceps Long Head"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 5009,
    name: "Dumbbell Kickback",
    primaryMuscles: ["Triceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 5010,
    name: "JM Press",
    primaryMuscles: ["Triceps"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 5011,
    name: "Bench Dip",
    primaryMuscles: ["Triceps"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 5012,
    name: "Single-Arm Cable Pushdown",
    primaryMuscles: ["Triceps"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },

  // ── LEGS ──
  {
    id: 6001,
    name: "Barbell Back Squat",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 6002,
    name: "Front Squat",
    primaryMuscles: ["Quads", "Core"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 6003,
    name: "Goblet Squat",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 6004,
    name: "Sumo Squat",
    primaryMuscles: ["Glutes", "Inner Thigh"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 6005,
    name: "Bulgarian Split Squat",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 6006,
    name: "Leg Press",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6007,
    name: "Hack Squat",
    primaryMuscles: ["Quads"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6008,
    name: "Leg Extension",
    primaryMuscles: ["Quads"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6009,
    name: "Leg Curl",
    primaryMuscles: ["Hamstrings"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6010,
    name: "Seated Leg Curl",
    primaryMuscles: ["Hamstrings"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6011,
    name: "Romanian Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 6012,
    name: "Nordic Hamstring Curl",
    primaryMuscles: ["Hamstrings"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 6013,
    name: "Glute Bridge",
    primaryMuscles: ["Glutes"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 6014,
    name: "Barbell Hip Thrust",
    primaryMuscles: ["Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 6015,
    name: "Walking Lunge",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 6016,
    name: "Reverse Lunge",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 6017,
    name: "Lateral Lunge",
    primaryMuscles: ["Glutes", "Inner Thigh"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 6018,
    name: "Standing Calf Raise",
    primaryMuscles: ["Calves"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6019,
    name: "Seated Calf Raise",
    primaryMuscles: ["Soleus"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6020,
    name: "Donkey Calf Raise",
    primaryMuscles: ["Calves"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6021,
    name: "Box Jump",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Plyometric",
    goal: Goal.weightGain,
    equipment: "Bodyweight",
  },
  {
    id: 6022,
    name: "Jump Squat",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Plyometric",
    goal: Goal.weightGain,
    equipment: "Bodyweight",
  },
  {
    id: 6023,
    name: "Step-Up",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 6024,
    name: "Sissy Squat",
    primaryMuscles: ["Quads"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 6025,
    name: "Wall Sit",
    primaryMuscles: ["Quads"],
    category: "Isometric",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 6026,
    name: "Single-Leg Romanian Deadlift",
    primaryMuscles: ["Hamstrings", "Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Dumbbell",
  },
  {
    id: 6027,
    name: "Pistol Squat",
    primaryMuscles: ["Quads", "Glutes"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 6028,
    name: "Cable Pull-Through",
    primaryMuscles: ["Glutes", "Hamstrings"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 6029,
    name: "Hip Abduction Machine",
    primaryMuscles: ["Glutes", "Hip Abductors"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 6030,
    name: "Hip Adduction Machine",
    primaryMuscles: ["Inner Thigh"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },

  // ── CORE / ABS ──
  {
    id: 7001,
    name: "Crunch",
    primaryMuscles: ["Abs"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7002,
    name: "Sit-Up",
    primaryMuscles: ["Abs"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7003,
    name: "Bicycle Crunch",
    primaryMuscles: ["Obliques", "Abs"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7004,
    name: "Reverse Crunch",
    primaryMuscles: ["Lower Abs"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7005,
    name: "Leg Raise",
    primaryMuscles: ["Lower Abs"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7006,
    name: "Hanging Leg Raise",
    primaryMuscles: ["Lower Abs", "Hip Flexors"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 7007,
    name: "Hanging Knee Raise",
    primaryMuscles: ["Abs", "Hip Flexors"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7008,
    name: "Plank",
    primaryMuscles: ["Core"],
    category: "Isometric",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7009,
    name: "Side Plank",
    primaryMuscles: ["Obliques"],
    category: "Isometric",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7010,
    name: "Russian Twist",
    primaryMuscles: ["Obliques"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7011,
    name: "Weighted Russian Twist",
    primaryMuscles: ["Obliques"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Plate",
  },
  {
    id: 7012,
    name: "Cable Crunch",
    primaryMuscles: ["Abs"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 7013,
    name: "Ab Roller",
    primaryMuscles: ["Abs", "Core"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Ab Wheel",
  },
  {
    id: 7014,
    name: "Dragon Flag",
    primaryMuscles: ["Abs", "Core"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 7015,
    name: "V-Up",
    primaryMuscles: ["Abs"],
    category: "Bodyweight",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7016,
    name: "Mountain Climber",
    primaryMuscles: ["Core", "Hip Flexors"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 7017,
    name: "Windshield Wiper",
    primaryMuscles: ["Obliques", "Abs"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 7018,
    name: "Hollow Hold",
    primaryMuscles: ["Abs", "Core"],
    category: "Isometric",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 7019,
    name: "Pallof Press",
    primaryMuscles: ["Core", "Obliques"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 7020,
    name: "Landmine Twist",
    primaryMuscles: ["Obliques", "Core"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },

  // ── CARDIO & FULL BODY ──
  {
    id: 8001,
    name: "Burpee",
    primaryMuscles: ["Full Body"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 8002,
    name: "Jumping Jack",
    primaryMuscles: ["Full Body"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 8003,
    name: "High Knees",
    primaryMuscles: ["Hip Flexors", "Cardio"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 8004,
    name: "Jump Rope",
    primaryMuscles: ["Calves", "Cardio"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Jump Rope",
  },
  {
    id: 8005,
    name: "Running (Treadmill)",
    primaryMuscles: ["Legs", "Cardio"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Treadmill",
  },
  {
    id: 8006,
    name: "Cycling (Stationary)",
    primaryMuscles: ["Legs", "Cardio"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Bike",
  },
  {
    id: 8007,
    name: "Rowing Machine",
    primaryMuscles: ["Back", "Legs", "Cardio"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Rower",
  },
  {
    id: 8008,
    name: "Elliptical",
    primaryMuscles: ["Full Body", "Cardio"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Elliptical",
  },
  {
    id: 8009,
    name: "Stair Climber",
    primaryMuscles: ["Glutes", "Quads"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Machine",
  },
  {
    id: 8010,
    name: "Battle Ropes",
    primaryMuscles: ["Shoulders", "Core"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Ropes",
  },
  {
    id: 8011,
    name: "Sled Push",
    primaryMuscles: ["Quads", "Glutes", "Chest"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Sled",
  },
  {
    id: 8012,
    name: "Sled Pull",
    primaryMuscles: ["Hamstrings", "Back"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Sled",
  },
  {
    id: 8013,
    name: "Bear Crawl",
    primaryMuscles: ["Full Body"],
    category: "Cardio",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },

  // ── OLYMPIC / POWER ──
  {
    id: 9001,
    name: "Power Clean",
    primaryMuscles: ["Full Body"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 9002,
    name: "Power Snatch",
    primaryMuscles: ["Full Body"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 9003,
    name: "Clean and Jerk",
    primaryMuscles: ["Full Body"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 9004,
    name: "Snatch",
    primaryMuscles: ["Full Body"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 9005,
    name: "Hang Clean",
    primaryMuscles: ["Full Body", "Traps"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 9006,
    name: "Clean Pull",
    primaryMuscles: ["Back", "Legs"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },
  {
    id: 9007,
    name: "Kettlebell Swing",
    primaryMuscles: ["Glutes", "Hamstrings"],
    category: "Olympic",
    goal: Goal.fatLoss,
    equipment: "Kettlebell",
  },
  {
    id: 9008,
    name: "Kettlebell Snatch",
    primaryMuscles: ["Full Body"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Kettlebell",
  },
  {
    id: 9009,
    name: "Kettlebell Clean",
    primaryMuscles: ["Full Body"],
    category: "Olympic",
    goal: Goal.powerLifting,
    equipment: "Kettlebell",
  },
  {
    id: 9010,
    name: "Medicine Ball Slam",
    primaryMuscles: ["Full Body", "Core"],
    category: "Plyometric",
    goal: Goal.fatLoss,
    equipment: "Medicine Ball",
  },
  {
    id: 9011,
    name: "Medicine Ball Throw",
    primaryMuscles: ["Chest", "Shoulders"],
    category: "Plyometric",
    goal: Goal.powerLifting,
    equipment: "Medicine Ball",
  },

  // ── FOREARMS & GRIP ──
  {
    id: 10001,
    name: "Wrist Curl",
    primaryMuscles: ["Forearms"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 10002,
    name: "Reverse Wrist Curl",
    primaryMuscles: ["Forearms"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Barbell",
  },
  {
    id: 10003,
    name: "Farmers Walk",
    primaryMuscles: ["Forearms", "Traps", "Core"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Dumbbell",
  },
  {
    id: 10004,
    name: "Plate Pinch",
    primaryMuscles: ["Forearms", "Grip"],
    category: "Isolation",
    goal: Goal.powerLifting,
    equipment: "Plate",
  },
  {
    id: 10005,
    name: "Dead Hang",
    primaryMuscles: ["Grip", "Forearms"],
    category: "Isometric",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },

  // ── GLUTES ──
  {
    id: 11001,
    name: "Cable Kickback",
    primaryMuscles: ["Glutes"],
    category: "Isolation",
    goal: Goal.muscleBuilding,
    equipment: "Cable",
  },
  {
    id: 11002,
    name: "Donkey Kick",
    primaryMuscles: ["Glutes"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 11003,
    name: "Fire Hydrant",
    primaryMuscles: ["Glutes", "Hip Abductors"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 11004,
    name: "Frog Pump",
    primaryMuscles: ["Glutes"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 11005,
    name: "Single-Leg Glute Bridge",
    primaryMuscles: ["Glutes"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Bodyweight",
  },
  {
    id: 11006,
    name: "Smith Machine Hip Thrust",
    primaryMuscles: ["Glutes"],
    category: "Strength",
    goal: Goal.muscleBuilding,
    equipment: "Machine",
  },
  {
    id: 11007,
    name: "Banded Lateral Walk",
    primaryMuscles: ["Glutes", "Hip Abductors"],
    category: "Bodyweight",
    goal: Goal.muscleBuilding,
    equipment: "Band",
  },
  {
    id: 11008,
    name: "Sumo Deadlift High Pull",
    primaryMuscles: ["Glutes", "Traps"],
    category: "Strength",
    goal: Goal.powerLifting,
    equipment: "Barbell",
  },

  // ── STRETCHING / MOBILITY ──
  {
    id: 12001,
    name: "Hip Flexor Stretch",
    primaryMuscles: ["Hip Flexors"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 12002,
    name: "Hamstring Stretch",
    primaryMuscles: ["Hamstrings"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 12003,
    name: "Pigeon Pose",
    primaryMuscles: ["Glutes", "Hip Flexors"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 12004,
    name: "World's Greatest Stretch",
    primaryMuscles: ["Full Body"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 12005,
    name: "Thoracic Rotation",
    primaryMuscles: ["Upper Back"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 12006,
    name: "Cat-Cow Stretch",
    primaryMuscles: ["Spine"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
  {
    id: 12007,
    name: "90/90 Hip Stretch",
    primaryMuscles: ["Glutes", "Hip Flexors"],
    category: "Flexibility",
    goal: Goal.fatLoss,
    equipment: "Bodyweight",
  },
];
