/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'icon' : string,
  'achievedAt' : Time,
  'description' : string,
}
export interface Badge { 'earnedDate' : Time, 'name' : string }
export interface BodyStats {
  'weight' : number,
  'arms' : number,
  'date' : Time,
  'hips' : number,
  'chest' : number,
  'legs' : number,
  'waist' : number,
}
export interface Exercise {
  'id' : bigint,
  'goal' : Goal,
  'name' : string,
  'primaryMuscles' : Array<string>,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export type Goal = { 'powerLifting' : null } |
  { 'fatLoss' : null } |
  { 'weightGain' : null } |
  { 'muscleBuilding' : null };
export interface Photo {
  'weight' : number,
  'blob' : [] | [ExternalBlob],
  'note' : string,
  'dateTaken' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'weight' : number,
  'height' : number,
  'joinDate' : Time,
  'goal' : Goal,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutSession {
  'id' : bigint,
  'duration' : bigint,
  'owner' : Principal,
  'date' : Time,
  'goal' : Goal,
  'exercises' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAchievement' : ActorMethod<[string, string], undefined>,
  'addBodyStats' : ActorMethod<
    [number, number, number, number, number, number],
    undefined
  >,
  'addExercise' : ActorMethod<[string, Array<string>, string, Goal], Exercise>,
  'addProgressPhoto' : ActorMethod<
    [number, string, [] | [ExternalBlob]],
    Photo
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[string], undefined>,
  'createUserProfile' : ActorMethod<
    [string, Goal, number, number],
    UserProfile
  >,
  'createWorkoutSession' : ActorMethod<
    [Array<string>, bigint, Goal],
    WorkoutSession
  >,
  'getAchievements' : ActorMethod<[Principal], Array<Achievement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEarnedBadges' : ActorMethod<[Principal], Array<Badge>>,
  'getExerciseLibrary' : ActorMethod<[], Array<Exercise>>,
  'getMovementSuggestions' : ActorMethod<[Goal, string], Array<Exercise>>,
  'getMyAchievements' : ActorMethod<[], Array<Achievement>>,
  'getMyBadges' : ActorMethod<[], Array<Badge>>,
  'getMyBodyStats' : ActorMethod<[], Array<BodyStats>>,
  'getMyProgressPhotos' : ActorMethod<[], Array<Photo>>,
  'getMyWorkouts' : ActorMethod<[], Array<WorkoutSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];