/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Goal = IDL.Variant({
  'powerLifting' : IDL.Null,
  'fatLoss' : IDL.Null,
  'weightGain' : IDL.Null,
  'muscleBuilding' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'goal' : Goal,
  'name' : IDL.Text,
  'primaryMuscles' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Photo = IDL.Record({
  'weight' : IDL.Float64,
  'blob' : IDL.Opt(ExternalBlob),
  'note' : IDL.Text,
  'dateTaken' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'joinDate' : Time,
  'goal' : Goal,
  'name' : IDL.Text,
});
export const WorkoutSession = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : Time,
  'goal' : Goal,
  'exercises' : IDL.Vec(IDL.Text),
});
export const Achievement = IDL.Record({
  'icon' : IDL.Text,
  'achievedAt' : Time,
  'description' : IDL.Text,
});
export const Badge = IDL.Record({ 'earnedDate' : Time, 'name' : IDL.Text });
export const BodyStats = IDL.Record({
  'weight' : IDL.Float64,
  'arms' : IDL.Float64,
  'date' : Time,
  'hips' : IDL.Float64,
  'chest' : IDL.Float64,
  'legs' : IDL.Float64,
  'waist' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAchievement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addBodyStats' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'addExercise' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, Goal],
      [Exercise],
      [],
    ),
  'addProgressPhoto' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Opt(ExternalBlob)],
      [Photo],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Text], [], []),
  'createUserProfile' : IDL.Func(
      [IDL.Text, Goal, IDL.Float64, IDL.Float64],
      [UserProfile],
      [],
    ),
  'createWorkoutSession' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Nat, Goal],
      [WorkoutSession],
      [],
    ),
  'getAchievements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarnedBadges' : IDL.Func([IDL.Principal], [IDL.Vec(Badge)], ['query']),
  'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getMovementSuggestions' : IDL.Func(
      [Goal, IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getMyAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getMyBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getMyBodyStats' : IDL.Func([], [IDL.Vec(BodyStats)], ['query']),
  'getMyProgressPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getMyWorkouts' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Goal = IDL.Variant({
    'powerLifting' : IDL.Null,
    'fatLoss' : IDL.Null,
    'weightGain' : IDL.Null,
    'muscleBuilding' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'goal' : Goal,
    'name' : IDL.Text,
    'primaryMuscles' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Photo = IDL.Record({
    'weight' : IDL.Float64,
    'blob' : IDL.Opt(ExternalBlob),
    'note' : IDL.Text,
    'dateTaken' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'joinDate' : Time,
    'goal' : Goal,
    'name' : IDL.Text,
  });
  const WorkoutSession = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : Time,
    'goal' : Goal,
    'exercises' : IDL.Vec(IDL.Text),
  });
  const Achievement = IDL.Record({
    'icon' : IDL.Text,
    'achievedAt' : Time,
    'description' : IDL.Text,
  });
  const Badge = IDL.Record({ 'earnedDate' : Time, 'name' : IDL.Text });
  const BodyStats = IDL.Record({
    'weight' : IDL.Float64,
    'arms' : IDL.Float64,
    'date' : Time,
    'hips' : IDL.Float64,
    'chest' : IDL.Float64,
    'legs' : IDL.Float64,
    'waist' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAchievement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addBodyStats' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'addExercise' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, Goal],
        [Exercise],
        [],
      ),
    'addProgressPhoto' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Opt(ExternalBlob)],
        [Photo],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Text], [], []),
    'createUserProfile' : IDL.Func(
        [IDL.Text, Goal, IDL.Float64, IDL.Float64],
        [UserProfile],
        [],
      ),
    'createWorkoutSession' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Nat, Goal],
        [WorkoutSession],
        [],
      ),
    'getAchievements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarnedBadges' : IDL.Func([IDL.Principal], [IDL.Vec(Badge)], ['query']),
    'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getMovementSuggestions' : IDL.Func(
        [Goal, IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getMyAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getMyBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getMyBodyStats' : IDL.Func([], [IDL.Vec(BodyStats)], ['query']),
    'getMyProgressPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getMyWorkouts' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };